### ISSUE TITLE
Support For Variable Long Names In .sym Files

### ISSUE THREAD

**Issue by garethellis0** [eerimoq/cantools#105]
It looks like currently we're ignoring the `/ln` flag on variables when parsing `.sym` files. Example below:
```
FormatVersion=6.0 // Do not edit this line!
Title="Untitled"

{SENDRECEIVE}

[FSM_ERRORS]
ID=040h	// This message contains a bit for each error that the FSM might throw
Len=8
Var=papps_out_of_range bit 0,1 /ln:"Primary Acceleration Pedal Position Sensor Out Of Valid Range"
```

Please let me know if you need any more info! Thanks!

**Comment by eerimoq** [comment]
Feel free to implement it! =)

**Comment by eerimoq** [comment]
By the way, `/ln` is not "Comment", it's "Long Name". `// ...` is the comment.

I'm working on several fixes and improvements to the SYM parser. This issue will likely be implemented.

**Comment by garethellis0** [comment]
Ah, that makes a lot more sense. I've updated the issue title to reflect this. Thank you!

**Comment by eerimoq** [comment]
I implemented comments, but not long name. I'll not implement long name as there is no obvious place for it in cantools database interface.
