### ISSUE TITLE
Read signal Initial value from dbc file not works

### ISSUE THREAD

**Issue by BrushLee90** [eerimoq/cantools#116]
After upgrading to the latest release. 
I found that it still can't read signal initial value from DBC file. 
I use a test dbc file (has uploaded as an attachment ), in which the signal "MRRSt" value in message 0x3a4 is set to 6. However, the read value is "None". 

<img width="360" alt="running snipshot" src="https://user-images.githubusercontent.com/41456116/53722777-3fa5d480-3ea1-11e9-9746-b98be9236637.png">

<img width="435" alt="mrrst in dbc snipshot" src="https://user-images.githubusercontent.com/41456116/53722866-6e23af80-3ea1-11e9-9921-2c1c2d42a42c.png">
[dbc_tes_file.zip](https://github.com/eerimoq/cantools/files/2925505/dbc_tes_file.zip)

**Comment by eerimoq** [comment]
The initial value is not yet extracted from any database format. Feel free to implement support for it for your particular format.

**Comment by eerimoq** [comment]
Try release 32.12.0, available on PyPI. It has intial support for inital values in DBC-files.

**Comment by BrushLee90** [comment]
Wonderful! Thank you for your work~~
