### ISSUE TITLE
SIG_VALTYPE_ & BO_TX_BU_

### ISSUE THREAD

**Issue by blackskandix** [eerimoq/cantools#12]
While parsing a few new .dbc-files, I got stuck with cantools when reaching lines with the commands:

- "SIG_VALTYPE_" 
- "BO_TX_BU_"
- "BA_DEF_REL_"
  - "BU_SG_REL_"
- "BA_DEF_DEF_REL_"
- "BA_REL_"
  - "BU_SG_REL_"

just wanted to let you know

------------------

SIG_VALTYPE sets the type of the value of a signal in a message - example:
SIG_VALTYPE_ 1649 dCANxxTime : 2; 
Sets the datatype in message (0x671), for signal (dCANxxTime) to "2" (IEEE Double)

**Comment by eerimoq** [comment]
Any possibility of sharing a DBC-file that can be used to reproduce the problem?

**Comment by eerimoq** [comment]
Added support for `SIG_VALTYPE_` in the DBC parser in 0183cdb2b77f038041b9b09aa5737ad960b8f0f6. 

Supporting floating point signals should be easy to add in the future, whenever they are needed by someone.

**Comment by blackskandix** [comment]
sorry, I'm not allowed to share the DBC-files 
I will see, if I can make a modified version of it, as soon as I find time

Anyways - thanks for responding

**Comment by eerimoq** [comment]
Would be very helpful! =)

**Comment by blackskandix** [comment]
update coming soon - don't close

**Comment by blackskandix** [comment]
I finally got used to the unknown commands. 
You got a pull request for db/formats/dbs.py(260):

I really can't provide you any dbc-files for test purposes - I'm sorry
But here are some sample lines for syntax understanding.

`BO_TX_BU_ 780 : ACC,Frontradar;`
Message with Id "780" is added to List of Senders in the Nodes "ACC" and "Frontradar".
It seems like a way to add nodes as senders after the basic "BO_" defintion.
As in one of my files:
```
BO_ 780 ACC_02: 8 ACC //only node "ACC" is sender in the message defintion
 SG_ ...
 .
 .
BO_TX_BU_ 780 : ACC,Frontradar; //later "Frontradar" gets listed as well
```
`BA_DEF_REL_ BU_SG_REL_ "GenSigTimeoutTime" INT 0 65535;`
"BA_DEF_REL_": relative attribute gets defined, like "BA_DEF_". 
"BU_SG_REL_": Prefix for type, like "BO_" in "BA_DEF_" for Messages
Here, I think, it means NodeToSignal-Realtionship - in my Vector CANdb++ it's displayed as "Node - Mapped Rx Signal"
The Following is a normal Attribute Definition: "attributeName" TYPE minValue maxValue;

`BA_DEF_DEF_REL_ "GenSigTimeoutTime" 0;`
relative attribute defintion of default value, like "BA_DEF_DEF_".
followed by the usual: "attributeName" valueDefault;

`BA_REL_ "GenSigTimeoutTime" BU_SG_REL_ MFK_3 SG_ 780 ACC_02_CRC 999;`
relative Attribute assignment, like "BA_"
"BU_SG_REL_" is a prefix again, like "SG_" - here: NodeToSignal-Realtionship "Node - Mapped Rx Signal".
Additionally to the "BA_" the node-name is given:
BA_RE_ "attributeName" BU_SG_REL_ nodeName SG_ messageID signalName value

( I'm not sure if "REL_" stands for relative or relation(ship) )
feel free to close
