### ISSUE TITLE
cantools.database.can.bus.py only used for .kcd parsing (need .dbc support)

### ISSUE THREAD

**Issue by anxuae** [eerimoq/cantools#127]
Hi,

Currently the database created from a .dbc file is always created sith an empty buses list.
See https://github.com/eerimoq/cantools/blob/4bde521fb35787776092d6ec31dc1356e4b3c35a/cantools/database/can/formats/dbc.py#L1352-L1356

However, information about the bus can be found in the DBC.  For instance in the one I'm using:

*Bus name:*

```
BA_DEF_  "DBName" STRING ;
BA_DEF_DEF_  "DBName" "";
BA_ "DBName" "Infotainment_AmplifierCAN";
```

*Bus baudrate:*

```
BA_DEF_  "Bauderate" INT 0 1000000;
BA_DEF_DEF_  "Bauderate" 125000;
BA_ "Bauderate" 125000;
```

Is it possible to add at least a `Bus()` in the list with the following info?

**Comment by eerimoq** [comment]
Feel free to implement it. I'll likely merge it =)

**Comment by anxuae** [comment]
Hi eerimoq,
Do you think the my pull request can be integrated?
Thanks
Anxuae

**Comment by eerimoq** [comment]
Sorry, I've been working on another project lately and forgot about your PR. I'll have a look now.

**Comment by eerimoq** [comment]
I added tests and refactored a bit.

There was a comment that the default baudrate was copied from kcd.py. I changed the default baudrate to None, or unavailable. Let me know if it should be 500000 instead and I'll change it back.

**Comment by anxuae** [comment]
Thanks a lot.
No matter of the default value, I did it only to be consistent with KCD parser.
