### ISSUE TITLE
Dump "IEEE Float" to DBC not supported?

### ISSUE THREAD

**Issue by qc17** [eerimoq/cantools#128]
Hi,
I have a signal:
`signal1 = cantools.database.can.Signal(sigName1, 0, 32,comment=comment1, receivers=receiver, is_float=True)`
that is added to a message/DBC. After dumping the database to a file the whole section with
`SIG_VALTYPE_ <can-id> <signame> : 1;`
is missing.

Could you please add this part in case the signal type is float or double?

Thank you for any help.

**Comment by eerimoq** [comment]
Feel free to add it yourself.

Thanks!

**Comment by karlding** [comment]
I ran into this issue as well, and have a patch ready to go. @qc17 are you still working on this? Otherwise, I'll just submit mine.

**Comment by qc17** [comment]
I only have a quick fix to dump IEEE-float signals right now. So you are welcome to submit your patch and then I will check my further need to dump doubles to a DBC.

**Comment by eerimoq** [comment]
Part of version 32.16.0, available on PyPI!
