### ISSUE TITLE
little/big endian

### ISSUE THREAD

**Issue by mmar2228** [eerimoq/cantools#139]
Dear all,

I have a simple question, when I use cantools dump I get a message tree.
Consider the basic example:

BO_ 496 ExampleMessage: 8 PCM1
 SG_ Temperature : 0|12@0- (0.01,250) [229.52|270.47] "degK"  PCM1,FOO
 SG_ AverageRadius : 6|6@0+ (0.1,0) [0|5] "m" Vector__XXX
 SG_ Enable : 7|1@0+ (1,0) [0|0] "-" Vector__XXX

The tree results as follows:

                          Bit

             7   6   5   4   3   2   1   0
           +---+---+---+---+---+---+---+---+
         0 |<-x|<---------------------x|<--|
           +---+---+---+---+---+---+---+---+
             |                       +-- AverageRadius
             +-- Enable
           +---+---+---+---+---+---+---+---+
         1 |-------------------------------|
           +---+---+---+---+---+---+---+---+
         2 |----------x|   |   |   |   |   |
     B     +---+---+---+---+---+---+---+---+
     y               +-- Temperature
     t     +---+---+---+---+---+---+---+---+
     e   3 |   |   |   |   |   |   |   |   |
           +---+---+---+---+---+---+---+---+
         4 |   |   |   |   |   |   |   |   |
           +---+---+---+---+---+---+---+---+
         5 |   |   |   |   |   |   |   |   |
           +---+---+---+---+---+---+---+---+
         6 |   |   |   |   |   |   |   |   |
           +---+---+---+---+---+---+---+---+
         7 |   |   |   |   |   |   |   |   |
           +---+---+---+---+---+---+---+---+

The @0 indicates BIG ENDIAN, what means the order MSB --- LSB in memory. In that case, does bit 6 (in byte 0) store the MSB of AverageRadius??

On the other hand, if I use another example (@1+ for LITTLE ENDIAN: order LSB --- MSB)

BO_ 2001Status: 8 Vector__XXX
 SG_ ID : 0|8@1+ (1,0) [0|0] "" Vector__XXX
......

with tree:

                 Bit

             7   6   5   4   3   2   1   0
           +---+---+---+---+---+---+---+---+
         0 |<-----------------------------x|
           +---+---+---+---+---+---+---+---+
             +-- ID
             ^
             ^
What is the meaning of marked bit 7? Does signal ID start at bit 7 (LSB)?? Or signal ID starts (LSB) at bit 0, as SG_ ID : 0|8@1+ indicates??

I appreciate your help!

Thanks you in advance

**Comment by eerimoq** [comment]
Maybe this helps: https://cantools.readthedocs.io/en/latest/#cantools.database.can.Message.layout_string
