### ISSUE TITLE
Pagination support in monitor subparser output

### ISSUE THREAD

**Issue by karlding** [eerimoq/cantools#140]
Currently when the output of the monitor subparser does not fit on the screen, it just overflows and there is no way of viewing the overflown messages. A workaround is to increase the number of rows your terminal can display (ie. decreasing the font size), but that's a hack at best.

I think it would be nice to implement some sort of pagination so that only the relevant visible slice is drawn as needed. This way, all the messages can be viewed, even if they don't all fit on one page of the terminal screen.

Would you be open to accepting a PR that adds this functionality?

**Comment by eerimoq** [comment]
Yes, that would be very welcome!
