### ISSUE TITLE
please update int(value) to int(Decimal(value)) to solve invalid literal error

### ISSUE THREAD

**Issue by yikangdu** [eerimoq/cantools#156]
some Vector tools generated dbc definition like this:
> BA_DEF_ SG_ "GenSigStartValue" INT -9.22337203685478E+018 1.84467440737096E+019;

so the code below can raise:
> ValueError: invalid literal for int() with base 10: '1.84467440737096E+019'

https://github.com/eerimoq/cantools/blob/6383c883f3faa1661dd97cc83b721de9508012ed/cantools/database/can/formats/dbc.py#L1339-L1343

the same problem happened in another project: [https://github.com/ebroecker/canmatrix/issues/168](url)

and the solution might be like:
`        if definition.type_name in ['INT', 'HEX']:
            value = int(Decimal(value))
`
I tested it in my dbc and it worked. I hope this may help you. ;-)

**Comment by eerimoq** [comment]
Fixed in 32.20.1.
