### ISSUE TITLE
Is it possible to view message frequency in cantools monitor?

### ISSUE THREAD

**Issue by thekenu** [eerimoq/cantools#159]
This issue is meant to be a question.

When using `cantools monitor`, is it possible to view the average frequency of a given message? Right now we I use `cantools monitor`, I see only the last relative timestampe for each message, but it's tough to tell if a message is being transmitted at 10Hz or 100Hz, for example.

**Comment by eerimoq** [comment]
That information is not available in the current implementation, sorry. Feel free to implement a PR as it sounds useful =)
