### ISSUE TITLE
as_kcd_string() return an object

### ISSUE THREAD

**Issue by rruvalcaba** [eerimoq/cantools#16]
Hi there,
I am trying to save a self generated can data base as kcd but the method "as_kcd_string()" is not returning a string as the method "as_dbc_string()" correctly does.

Instead is returning a '<cantool.db.database.Database object at 0x0.....>'

Code:
 # I was trying it once with a dbc file
    db = cantools.db.File()
    filename = r"...\tests_cantools\files\example.dbc"
    db.add_dbc_file(filename)

# and a second time with a kcd file
    db = cantools.db.File()
    filename = r"...\tests_cantools\files\example.kcd"
    db.add_kcd_file(filename)

    signals = [cantools.db.Signal(name='POPOTO_SIG',  start=0, length=4, nodes=['foo'], byte_order='big_endian', is_signed=False, scale=1.0, offset=10, minimum=10.0, maximum=100.0, unit='m/s', choices=None, comment=None)]

    message = cantools.db.Message(frame_id=37, name='PEPETO_message',  length=8,  nodes=['bar'],  signals=signals, comment='')

    db.add_message(message)

    texto = db.as_kcd_string()  # this one returns an object
    texto1 = db.as_dbc_string()  # this one works correctly

In both cases "as_kcd_string()" returns an oject

**Comment by eerimoq** [comment]
Yeah, the as_kcd_string() function is not yet implemented. It's just there for load/as symmetry in the interface. I hav eno immediate plans on implementing it, feel free to help out.
