### ISSUE TITLE
decode tool

### ISSUE THREAD

**Issue by Puude** [eerimoq/cantools#160]
Hi,

When i do a candump i received all the messages off the CAN network.
For decode the data i use the cantools decode tool. It works perfect.
Only the decode tool look to the CAN id and not to the PGN. (http://tiny.cc/gxrqdz) of the data frame.
Is it possible to drop the source address of the CAN id and fil 254 at that place?

Thanks in advance

**Comment by eerimoq** [comment]
There is a frame if mask argument to ignore masked bits in the frame ids on lookup in the database. Other than that there is nothing that can help you in the current implementation.

https://github.com/eerimoq/cantools/blob/master/cantools/subparsers/decode.py#L77
https://github.com/eerimoq/cantools/blob/master/cantools/database/__init__.py#L98
