### ISSUE TITLE
Double newline in dbc dump on Windows

### ISSUE THREAD

**Issue by geo4711** [eerimoq/cantools#163]
I use cantools on a Windows machine.
I try to apply specific patches to given dbc files (which are created on Windows, too).

The input files are coded with CR+LF as a newline.
The output files, however, show kind of doubles newlines: CR+CR+LF

It's not a big issue, afaik other tools have no problems reading those files, but it doesn't look very nice in text mode.

**Comment by geo4711** [comment]
The function `write()` called in `database.__init__.dump_file()` seems to replace `\n` by `\r\n`. The original string already contains `\r\n` as line breaks, which will result in `\r\r\n`, what can be seen in the file.

Tested/reproduced with:
```
with cantools.compat.fopen("out.txt", "w", encoding='cp1252') as x:
	x.write("Hello\nWorld")
```

**Comment by geo4711** [comment]
I've found the reasen for that behaviour.
The `write()` function (python built-in) replaces `\n` by the operating system's standard newline `os.linesep`, which is `\r\n` on windows.

I could imagine to fix that by one of the following measures:
1. force `write()` to **not** modify any newline: parameter `newline=''`
2. replace `\r\n` by `\n` in the whole module

The python documentation recommends the seconde way. If we want to enforce the dbc to be "windows like" on all operating systems, than we should prefer solution one.

**Comment by eerimoq** [comment]
Let's write \r\n to file regardless of OS, as that is what cantools is currently designed for. I guess that means alternative 1. Let's hope it is easy to implement. =)

**Comment by geo4711** [comment]
Ok, do we have to take care about newline in other output file formats? As far as I've seen, dbc is the only plain text format currently supported for output, isn't it?

**Comment by eerimoq** [comment]
KCD has support for output as well. It's an XML format where line ending is not important to other tools.

I suggest forcing \r\n output for DBC, and OS dependent line ending for KCD.

**Comment by geo4711** [comment]
That's fine :-)
I'll skip the old pull request, which went for the other way, and create another one for solution 1.

**Comment by eerimoq** [comment]
Ok!
