### ISSUE TITLE
cantools don't work in python3

### ISSUE THREAD

**Issue by loci41** [eerimoq/cantools#172]
Hello, i wrote a python-programm which can read and save CAN-data on a raspberry pi 3B+. When I start it in the terminal of the raspberry in python, it works. But when i start it in python3, it don't work. 

ERROR:
File "program.py", line11, in <module>
      import cantools
ModuleNotFoundError: No module named 'cantools'

**Comment by eerimoq** [comment]
Looks like you havn't installed cantools. I've not used Raspberry PI myself, but I think you can install it with pip, or possibly pip3?

**Comment by loci41** [comment]
thanks for your fast advice. I found my mistake. 
I just installed cantools for python --> pip install cantools
now i installed it for python3 --> pip3 install python
