### ISSUE TITLE
one interesting question

### ISSUE THREAD

**Issue by jingyuan1994** [eerimoq/cantools#202]
Hi eerimoq,

There is one interesting question I found. I succeed to decode the message and get the value from special signals. But for the same message file (blf), combining with the results I decoded and the value which run in CANoe, there are a little bit difference, just a little, for example the data is decoded as 15 but 13 in CANoe . Something interesting is, the trend is totally right, but there are some difference in value, seems like any parameter didn't multiply. Is that the problem from my dbc? Or CANoe has any special algorithm?

If you need me to share code or something else, in mail will be better.

Thanks!

**Comment by eerimoq** [comment]
Hi! Feel free to email more information to erik.moqvist@gmail.com. Try to be very specific to make it easy for me to understand the problem and quickly solve it.

**Comment by jingyuan1994** [comment]
Hi, I have send you the email by using my work email. Have you found it? If you did receive it, please check the junk mail. 

Thanks again!

**Comment by eerimoq** [comment]
Checking tonight.
