### ISSUE TITLE
34.2.0 breaks deep copying a database

### ISSUE THREAD

**Issue by jauerb** [eerimoq/cantools#204]
deep copying a database worked in previous versions but now errors out with
`TypeError: can't pickle bitstruct.c.CompiledFormatDict objects`

**Comment by eerimoq** [comment]
Make sure you have the latest version of bitstruct installed.

pip3 install -U bitstruct

That may fix it. If not I'll have a look at it.

**Comment by jauerb** [comment]
Ah, that did fix it, thanks!
