### ISSUE TITLE
can not install for SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by savagesheller** [eerimoq/cantools#217]
SyntaxError occur when i install cantools by 'pip install cantools':
  Downloading https://files.pythonhosted.org/packages/76/6d/a4342d968eeff3a5f35556a52a1310717558612fedbaa1c7e80626163ce4/argparse_addons-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Ca3gh3/argparse-addons/setup.py", line 4, in <module>
        import argparse_addons
      File "argparse_addons.py", line 19
        f'{string} is not in the range {self.minimum}..{self.maximum}')
                                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Ca3gh3/argparse-addons/

**Comment by eerimoq** [comment]
See #211.
