### ISSUE TITLE
Invalid DBC syntax: 'BA_REL_ "GenSigComment" BU_SG_REL_ ICCM_CE SG_ 569 SomeString >!<"";': Expected positive integer."

### ISSUE THREAD

**Issue by sietschie** [eerimoq/cantools#22]
Using Python 3.4.4 and cantools 16.2.0 I get the following error when trying to load my DBC:

> cantools.db.UnsupportedDatabaseFormatError: DBC: "Invalid DBC syntax at line 5569, column 80: 'BA_REL_ "GenSigComment" BU_SG_REL_ ICCM_CE SG_ 569  SomeString >!<"";': Expected positive integer."

Is it possible to add support for this?

**Comment by eerimoq** [comment]
Almost anything is possible. Can you provide a DBC-file I can use for testing, to make sure the implementaiton works?

**Comment by sietschie** [comment]
I am afraid I am not allowed to give out the original DBC file. And I don't know enough about DBCs to produce my own file. Maybe you can point me in the right directions so I can make the changes myself?

**Comment by eerimoq** [comment]
Have a look here: https://github.com/eerimoq/cantools/blob/master/cantools/db/formats/dbc.py#L305-L313

There is the part of the grammar where your DBC fails. Looks like the grammar should not only allow positive integer, but maybe floating point numbers?

**Comment by eerimoq** [comment]
I suggest that you add the failing DBC-line here: https://github.com/eerimoq/cantools/blob/master/tests/files/foobar.dbc#L83

And then modify the tests in tests/test_cantools.py to make them pass.

**Comment by DC-Melo** [comment]
my database is like this：
 BA_DEF_ BU_  "NmStationAddress" HEX 0 0;
   1 BA_DEF_ BU_  "NodeLayerModules" STRING ;
1811 BA_DEF_REL_ BU_BO_REL_  "GenMsgCycleTimeFast" INT 0 65535;
   1 BA_DEF_REL_ BU_BO_REL_  "GenMsgNrOfRepetition" INT 0 65535;
   2 BA_DEF_REL_ BU_BO_REL_  "GenMsgDelayTime" INT 0 65535;
   3 BA_DEF_REL_ BU_BO_REL_  "GenMsgStartDelayTime" INT 0 65535;
   4 BA_DEF_DEF_  "BusType" "";
   5 BA_DEF_DEF_REL_ "GenMsgCycleTimeFast" 0;

so：i change the code to：
        attribute_definition_rel = Sequence(
            'BA_DEF_REL_',
            Optional(choice('BU_SG_REL_','BU_BO_REL_')),
            'STRING',
            'WORD',
            choice(DelimitedList('STRING'), OneOrMore('NUMBER')),
            ';')

now：it is ok

**Comment by Guemi** [comment]
I've modify it the dbc.py file to the following:
`        attribute_definition_rel = Sequence(
            'BA_DEF_REL_',
            Optional(choice('BU_SG_REL_', 'BU_BO_REL_')),
            'STRING',
            'WORD',
            Optional(choice(DelimitedList('STRING'), OneOrMore('NUMBER'))),
            ';')`
to support a dbc that looks like this:
`BA_DEF_REL_ BU_BO_REL_  "Frame1" STRING ;
BA_DEF_REL_ BU_BO_REL_  "Frame2" HEX 0 1407;
BA_DEF_REL_ BU_BO_REL_  "Event1" INT 10 10000;
BA_DEF_REL_ BU_SG_REL_  "Signal1" ENUM  "Yes","No";`
