### ISSUE TITLE
Debian packaging release

### ISSUE THREAD

**Issue by tonybaltovski** [eerimoq/cantools#224]
Hi, 

I was wondering you would be open to doing a Debian packaging release for this repo into Ubuntu and Debian?  I am in a situation where I cannot use `pip`.  I could do a release myself but feel others might benefit having it available.

Cheers,

Tony

**Comment by eerimoq** [comment]
Sure, if someone creates the package and maintains it. I have no interest in it myself. =)

**Comment by tonybaltovski** [comment]
Fair enough.  I will do a PR for the packaging eventually. Closing this based on that.

**Comment by Timple** [comment]
@tonybaltovski did you ever make progress on this?

**Comment by tonybaltovski** [comment]
@Timple no, we did not end up needing this.
