### ISSUE TITLE
Wrong frame_id for extended frames

### ISSUE THREAD

**Issue by Florian6451** [eerimoq/cantools#227]
When I try to read the "frame_id" from a message of the type "CAN Extended" I will always get a wrong value.
For normal frames I am getting the right frame_id.

For example:
frame_id in dbc: 2527679635
return of msg.frame_id: 380195987

Is it because the frame_id_bit_length > 29 ?
If yes, why am I not getting any error ?

**Comment by eerimoq** [comment]
It's because the most significant bit in the DBC is not part of the frame id, but a flag that is set for extended frames.

**Comment by DaGuich** [comment]
But shouldn't we translate the `msg.frame_id` to its actual identifier then?

**Comment by eerimoq** [comment]
It already is, right? If not, please provide an example.
