### ISSUE TITLE
decode_message MemoryError

### ISSUE THREAD

**Issue by Pi57** [eerimoq/cantools#232]
Hello,

I'm quite new in python, and I'm trying to use cantools, mainly the CAN decode_message feature.

I'm using Python 3.9 and cantools 35.4.0

My issue is that, when I parse a blf file and decode each message, I can see the memory usage increase until I got an error MemoryError and the script stop.

My loop is this one :

>      for file in fileList:
>          # Read BLF
>          print("Loading BLF file from '{}'.".format(inputFilePath + file))
>          log = can.BLFReader(inputFilePath + file)
> 
>          logFull = list(log)
> 
>          # Keep only message in the filter
>          logLight = [msg for msg in logFull if msg.arbitration_id in keepMsg]
> 
>          for msg in logLight:
>              decodedMessage = db.decode_message(msg.arbitration_id, msg.data)

Maybe I don't use the function correctly ? I can get decoded data correctly, but there is this memory issue.
If I remove the line with decode_message, the memory is fine.

Maybe someone have a clue to solve this issue ?

Thanks

**Comment by eerimoq** [comment]
You are not using this project. Create an issue here instead: https://github.com/hardbyte/python-can

**Comment by Pi57** [comment]
The project you indicate is for the BLFReader I think, I don't have any issue with this feature.

I got the memory issue when I use the decoding function from this project I think ?

**Comment by eerimoq** [comment]
Ohh, sorry, you are right. Could you provide the traceback?

**Comment by Pi57** [comment]
You can find the traceback here :
```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
  File "test.py", line 38, in <listcomp>
MemoryError
[9952] Failed to execute script test
```

line 38 is :
`logLight = [msg for msg in logFull if msg.arbitration_id in keepMsg]`

and memory is full

**Comment by eerimoq** [comment]
Well, that's before cantools is used, right? So the problem is that the log is too big and your machine runs out of memory?

**Comment by Pi57** [comment]
Each log files are around 1.4 MB.

If I parse all files without decoding them, I have no issue with the memory

**Comment by eerimoq** [comment]
Could you provide an example I can use to reproduce the issue? Makes it easier for me to troubleshoot it.

**Comment by Pi57** [comment]
You mean, you want a blf and a dbc file to test it ?

**Comment by eerimoq** [comment]
I think I managed to reproduce it myself.

**Comment by eerimoq** [comment]
Update the cantools dependency bitstruct to version 8.11.1.  Something similar to `pip install -U bitstruct`. `-U` is important.

**Comment by Pi57** [comment]
ok I will try and let you know

Thanks :)

**Comment by Pi57** [comment]
After updating bitstruct dependency, memory issue disappear :)

Thanks for your quick help !
