### ISSUE TITLE
For database objects, attribute_definition_defaults and attribute_definitions should defaults to dicts, not lists

### ISSUE THREAD

**Issue by rjw245** [eerimoq/cantools#24]
Otherwise, I see the following error:
    default_send_type = database.attribute_definition_defaults['GenMsgSendType']
TypeError: list indices must be integers, not str

**Comment by rjw245** [comment]
This also applies to File objects

**Comment by eerimoq** [comment]
These attributes in the Database class is an ugly hack to preserve the information from a parsed DBC-file. The interface to access such attributes should be reworked to be clean and useful. I have not made up my mind yet of how to design the final interface. Any ideas?

**Comment by rjw245** [comment]
I think in either case, you're mapping the attribute name to a value right? Dictionary seems most appropriate for both, IMO.

**Comment by eerimoq** [comment]
Does it help you if they are both dictionaries? What is the use case? As said, the storage of attributes should be redesigned at some point, and maybe dictionaries will be used then.

Will you submit a PR with a fix for the wrong default values?
