### ISSUE TITLE
Parsing CDD File 

### ISSUE THREAD

**Issue by JosephGeorges** [eerimoq/cantools#250]
Hello, 

I am having some difficulty parsing a CDD file with cantools library. I have the cdd file in the same directory as my python script, so I just pass in the file name. My code looks like this:

```
filename = 'example.cdd' 
cdd_file = cantools.db.load_file(filename)
example_did = cdd_file.get_did_by_name('Application Software Identification')
print(example_did)
```

I want to print out the DID information by giving the DID itself or the did name. But on execution I receive the following: 

> Overwriting DID '_____' in the identifier to DID dictionary because they have identical identifiers 0x1.
> KeyError: 'Application Software Identification'

Any idea how to do this? I have tried parsing and printing out messages from a DBC file as well and that works fine. It seems like parsing a CDD file does not work the same way. Thank you for any help in advance!

**Comment by eerimoq** [comment]
The CDD likely ha lots of bugs s it is barely used. Unfortunately no one is fixing the bugs as far as I know. Pull requests are very welcome.

**Comment by oomzay** [comment]
I have rather replicated this issue with https://github.com/eerimoq/cantools/issues/290
I am currently experimenting with solutions that enhance, but don't break the current interface.

**Comment by oomzay** [comment]
Closing as duplicated/superceded by https://github.com/eerimoq/cantools/issues/290
