### ISSUE TITLE
conda-forge recipes

### ISSUE THREAD

**Issue by danielhrisca** [eerimoq/cantools#28]
Hello,

congratulations for **cantools** and **bitstruct** packages!

I'm using them in my package [asammdf](https://github.com/danielhrisca/asammdf). A few days ago I made my package available to anaconda users on the conda-forge channel. Do you think you can also provide your packages on conda-forge? It's not so hard since they are pure-python.

**Comment by eerimoq** [comment]
Hi,

feel free to add the packages yourself. =)

**Comment by danielhrisca** [comment]
Hello,

I'll also add you to the maintainers list.

**Comment by eerimoq** [comment]
Ok
