### ISSUE TITLE
hey do you know how to use regular expression to simplify your project?

### ISSUE THREAD

**Issue by AlvinYee** [eerimoq/cantools#29]
hey do you know how to use regular expression to simplify your project with one fifth or even one tenth of your code, and ten times of readability? 
https://github.com/AlvinYee/GodLoveMe/blob/AlvinYee-patch-2/dbcParser/dbcParser

**Comment by eerimoq** [comment]
There are indeed simplification to be made, but not using regular expressions. I'll stick to pyparsing or similar package.
