### ISSUE TITLE
FEATURE REQUEST: javascript implementation

### ISSUE THREAD

**Issue by euberdeveloper** [eerimoq/cantools#302]
It would be beautiful to have a javascript implementation that from a schema generates the code in javascript or typescript for serialize or deserialize the can messages.

**Comment by zabealbe** [comment]
Yes please it would be awesome to use THE INDUSTRY STANDARD for AUTOMOTIVE in my NODEJS WEB APP.

**Comment by euberdeveloper** [comment]
I do not think that a webapp would be a good usecase for this project.

**Comment by andlaus** [comment]
this is out of scope for this project: as far as I'm concerned cantools is going you stay python only. Writing a JavaScript code generator similar to the C one should not be too difficult, though. Closing this issue for now.

**Comment by juleq** [comment]
A note to node.js developers: You can use the fabulous socketcan package by sebi2k1 to encode/decode and send/receive on Linux platforms. It uses kcd as its definition file but you can use cantools to convert dbc->kcd. And if you suffer from boredom you could probably fairly easy do a PR for a js dbc parser for the socketcan project.
