### ISSUE TITLE
Arxml support

### ISSUE THREAD

**Issue by danielhrisca** [eerimoq/cantools#31]
Hello Erik,

what do you think about adding arxml format to the supported database formats?

https://automotive.wiki/index.php/AUTOSAR_XML_Schema

**Comment by danielhrisca** [comment]
I could not find the specification for this format but a starting point could be _canmatrix_ 

https://github.com/ebroecker/canmatrix

**Comment by eerimoq** [comment]
Hmms... maybe you can use canmatrix instead? =)

**Comment by danielhrisca** [comment]
I'm already using _canmatrix_ because it supports arxml. Initially I've used _cantools_ to handle DBC files.

I appreciate _cantools_ and I think it will be a very nice feature to have.

**Comment by eerimoq** [comment]
I might implement it. Though, it would be very helpful if you could start by writing a bunch of tests to verify that the implementation works as expected. It's unlikely I'll start the implementation without provided tests as I have no experience of ARXML and no possibility to easily test it.

**Comment by eerimoq** [comment]
Any progress?
