### ISSUE TITLE
Question: state of message/signal attributes?

### ISSUE THREAD

**Issue by rjw245** [eerimoq/cantools#38]
Hi, just wanted to ask a question.

The last I checked, cantools did not properly support database-, message-, and signal-level attributes passed to constructors. Has this since been updated? I am hoping to build up a CAN database using cantools classes and assign certain attributes to the objects within the database, and finally render this to a DBC file. Is this possible at this time?

Thanks

**Comment by rjw245** [comment]
I last asked about this in issue #27

**Comment by eerimoq** [comment]
No, attributes are still not properly implemented, sorry.
