### ISSUE TITLE
feature request: message.decode(data, decode_choices=False)

### ISSUE THREAD

**Issue by karlpeterhugo** [eerimoq/cantools#6]
Hi,
I suggest to support a parameter to disable the decoding of signal choices (e.g. enumerated signal values such as 'ON', 'OFF') and to decode the integer value instead.
This can be useful for post processing.

**Comment by eerimoq** [comment]
Sounds great, easy to implement and useful. Would be nice if you could implement it and submit a pull request.

**Comment by eerimoq** [comment]
At the same time we could make scaling optional, an there sometimes are rounding errors.

**Comment by eerimoq** [comment]
Your suggestions has been implemented and released in 9.1.0!

**Comment by karlpeterhugo** [comment]
Hi Erik, the new feature is great and helps me using your cantools package out of the box.
Thank you for implementing it!

**Comment by eerimoq** [comment]
You're welcome :)
