### ISSUE TITLE
Message.nodes returns string

### ISSUE THREAD

**Issue by zlim00** [eerimoq/cantools#7]
Message.nodes returns a string not a list as the documentation suggests

**Comment by eerimoq** [comment]
Please give an example showing your input and output, and I can create a unit test using that data, and then make nodes a list instead of a string.

**Comment by zlim00** [comment]
```
database = cantools.db.load_file("database.dbc")
for message in database.messages:
        print repr(message.nodes)
```
output are strings, method documentation states output should be a lists

**Comment by eerimoq** [comment]
Fixed on master, please give it a try and I'll release it to PyPi if you are satisfied.

**Comment by zlim00** [comment]
seems to work 👍 
Related question, how is multiple nodes for a message defined in the database? (can't find a specification and can't test with candb++)

**Comment by eerimoq** [comment]
I don't know if the DBC format can have multiple nodes (or producers) per message. Since this package is intended to support multiple database formats sharing a common API I decided to make message nodes a list as some format may allow multiple nodes per message. Good or bad decision is for the future to decide. =)

**Comment by eerimoq** [comment]
I uploaded a new release to PyPi, 10.0.0. Let's hope not too many users relied on the nodes as a string. Anyway, it's very easy to port the code to the new version by adding `[0]` after the nodes member.

**Comment by artemiljin** [comment]
Hi,
  DBC format supports multiple nodes associated with different ECUs, it'd be nice to have merging of nodes, ecus in add_dbc_file method.

**Comment by eerimoq** [comment]
Hello,

feel free to implement it. =)

**Comment by artemiljin** [comment]
> Hello,
> 
> feel free to implement it. =)

Nice, just wanted to be sure that it wasn't planned.
