### ISSUE TITLE
Lack of message type and signal default value information

### ISSUE THREAD

**Issue by BrushLee90** [eerimoq/cantools#91]
Message or frame type and signal initial value information sometimes are also needed from dbc file.
Message type, such as can can standard, can extended, can FD standard. example as following:
![image](https://user-images.githubusercontent.com/41456116/50814835-fa0fd400-1355-11e9-98ab-8767e5887e3c.png)

signal attributions as following:
![image](https://user-images.githubusercontent.com/41456116/50814982-7bfffd00-1356-11e9-8ead-6db30d3d38f6.png)

So, the two attribution can be added?  Thank you for hard work~

**Comment by eerimoq** [comment]
Please attach a valid DBC-file with these attributes.

**Comment by eerimoq** [comment]
I cannot find the message nor the signal from your first comment in the DBC file. Please write a better description of the issue with all information required to implement support for it.

**Comment by IvanEscamilla** [comment]
Hi, I just made a PR that solves the problem of the signal initial value. #112

**Comment by BrushLee90** [comment]
got it. thank you!
